# Generated by Django 4.2.14 on 2024-07-24 14:45

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название статьи"),
                ),
                ("text", models.TextField(verbose_name="Текст статьи")),
                (
                    "body",
                    mdeditor.fields.MDTextField(
                        blank=True, null=True, verbose_name="Markdown редактор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
