# Generated by Django 4.2.14 on 2024-07-24 14:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body",
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=mdeditor.fields.MDTextField(
                blank=True, null=True, verbose_name="Markdown редактор"
            ),
        ),
    ]
